version: '3'

services:
  node0:
    container_name: cronosnode0
    image: "cronos/node"
    build:
      context: cronos
      dockerfile: Dockerfile
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./cronos-devnet/cronos_777-1/node0:/app/home:Z
    command:
      - /cronosd start --home /app/home
    networks:
      localnet-cronos:
        ipv4_address: 192.167.11.2

  node1:
    container_name: cronosnode1
    image: "cronos/node"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./cronos-devnet/cronos_777-1/node1:/app/home:Z
    command:
      - /cronosd start --home /app/home
    depends_on:
      - node0
    networks:
      localnet-cronos:
        ipv4_address: 192.167.11.3

  node2:
    container_name: cronosnode2
    image: "cronos/node"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./cronos-devnet/cronos_777-1/node2:/app/home:Z
    command:
      - /cronosd start --home /app/home
    depends_on:
      - node0
    networks:
      localnet-cronos:
        ipv4_address: 192.167.11.4

networks:
  localnet-cronos:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.11.0/24